# frontend/Dockerfile.dev

FROM node:20-alpine

WORKDIR /app

# Kopiujemy tylko pliki potrzebne do instalacji zależności
COPY package.json pnpm-lock.yaml ./

# Instalujemy pnpm i zależności
RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install --shamefully-hoist

# --- USUNIĘTO LINIĘ "COPY . ." ---
# Kod źródłowy zostanie dostarczony przez volume mount w docker-compose.dev.yml,
# więc nie kopiujemy go do obrazu. To zapobiega konfliktom.

# Port, na którym działa serwer deweloperski Vite
EXPOSE 5173

# Definiujemy domyślną komendę (chociaż jest nadpisywana w docker-compose)
CMD ["pnpm", "run", "dev", "--host"]