services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: pnpm run dev --host

  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  celery_worker:
    volumes:
      - ./backend:/app
    command: celery -A app.worker.celery_app worker --loglevel=info

  celery_beat:
    volumes:
      - ./backend:/app
